export const FETCH_CHAPTERS = "FETCH_CHAPTERS";
export const GET_CHAPTERS = "GET_CHAPTER";
export const CREATE_CHAPTER = "CREATE_CHAPTER";
export const UPDATE_CHAPTER = "UPDATE_CHAPTER";
export const DELETE_CHAPTER = "DELETE_CHAPTER";