export const FETCH_COURSES = "FETCH_COURSES";
export const GET_COURSES = "GET_COURSES";
export const GET_COURSES_ALL = "GET_COURSES_ALL";
export const CREATE_COURSE = "CREATE_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
